// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnEc-NDIoxiaFeIjxfRy6B7EBv06YX5ds',
    appId: '1:439587146616:web:7181389f14c71fb382568d',
    messagingSenderId: '439587146616',
    projectId: 'notes-app-56306',
    authDomain: 'notes-app-56306.firebaseapp.com',
    storageBucket: 'notes-app-56306.firebasestorage.app',
    measurementId: 'G-E0VXSRNBJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjlj1JfBRAQwiXlLnw6SpdHBIM0OecB8c',
    appId: '1:439587146616:android:6f97392e5039344582568d',
    messagingSenderId: '439587146616',
    projectId: 'notes-app-56306',
    storageBucket: 'notes-app-56306.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3iGWMX_fQEwZWjc3Xc5M33FLH1gACCsM',
    appId: '1:439587146616:ios:f22a677286eb22ca82568d',
    messagingSenderId: '439587146616',
    projectId: 'notes-app-56306',
    storageBucket: 'notes-app-56306.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3iGWMX_fQEwZWjc3Xc5M33FLH1gACCsM',
    appId: '1:439587146616:ios:f22a677286eb22ca82568d',
    messagingSenderId: '439587146616',
    projectId: 'notes-app-56306',
    storageBucket: 'notes-app-56306.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnEc-NDIoxiaFeIjxfRy6B7EBv06YX5ds',
    appId: '1:439587146616:web:bd787bbf04a57a2982568d',
    messagingSenderId: '439587146616',
    projectId: 'notes-app-56306',
    authDomain: 'notes-app-56306.firebaseapp.com',
    storageBucket: 'notes-app-56306.firebasestorage.app',
    measurementId: 'G-D48FT1LFSG',
  );
}


